<a href="https://colab.research.google.com/github/ekaropolus/recommender_and_graph_spp/blob/main/Google%20Colab%20Notebooks/DS_Neo4j_ExpertIA_Sustainable_Public_Policies_MX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install neo4j
! pip install expertai-nlapi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting neo4j
  Downloading neo4j-5.1.0.tar.gz (173 kB)
     |████████████████████████████████| 173 kB 30.0 MB/s
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from neo4j) (2022.4)
Building wheels for collected packages: neo4j
  Building wheel for neo4j (setup.py) ... done
  Created wheel for neo4j: filename=neo4j-5.1.0-py3-none-any.whl size=248097 sha256=2c0bcc458a9c6fa3e03131a1a532d15b4e54b7fbeb6ddb6aacc09dc740b3fa64
  Stored in directory: /root/.cache/pip/wheels/64/96/da/c30ec8577a970eadecc436103fbcbf7af1d6398d0ebe32cbab
Successfully built neo4j
Installing collected packages: neo4j
Successfully installed neo4j-5.1.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting expertai-nlapi
  Downloading expertai_nlapi-2.4.1-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 6.7 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from expertai-nlapi) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->expertai-nlapi) (2022.9.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->expertai-nlapi) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->expertai-nlapi) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->expertai-nlapi) (1.24.3)
Installing collected packages: expertai-nlapi
Successfully installed expertai-nlapi-2.4.1

In [26]:
from neo4j import GraphDatabase
import logging
from neo4j.exceptions import ServiceUnavailable
import pandas as pd
import json
import os
from expertai.nlapi.cloud.client import ExpertAiClient

In [27]:
os.environ["EAI_USERNAME"] = 'hi@hadox.org'
os.environ["EAI_PASSWORD"] = 'RYD.Lq5Et4nT4T4'
client = ExpertAiClient()
language= 'es'

In [28]:
%cd /content/drive/MyDrive/Proyectos 2022/01 Hackahton Expert.ia Neurolitks

/content/drive/MyDrive/Proyectos 2022/01 Hackahton Expert.ia Neurolitks

In [6]:
df_pp = pd.read_parquet('df_pp_2.parquet.gzip')

In [7]:
df_pp.head()

,id,group,description,lemmas,syncons
0,AG1,1,"i. aguascalientes educado, integrado y equitativo","[{'id': 'AG1', 'score': 44.09, 'value': 'educa...","[{'id': 'AG1', 'lemma': 'cortés', 'score': 43...."
1,AG2,1,"ii. aguascalientes derecho, seguro y libre","[{'id': 'AG2', 'score': 99.0, 'value': 'ii. ag...","[{'id': 'AG2', 'lemma': 'derecho', 'score': 5...."
2,AG3,1,"iii. aguascalientes con gobierno íntegro, aust...","[{'id': 'AG3', 'score': 46.59, 'value': 'gobie...","[{'id': 'AG3', 'lemma': 'ministerio', 'score':..."
3,AG4,1,"iv. aguascalientes competitivo, diversificado ...","[{'id': 'AG4', 'score': 43.79, 'value': 'diver...","[{'id': 'AG4', 'lemma': 'diversificado', 'scor..."
4,AG5,1,"v. aguascalientes responsable, sostenible y li...","[{'id': 'AG5', 'score': 90.19, 'value': 'v. ag...","[{'id': 'AG5', 'lemma': 'diligente', 'score': ..."

In [9]:
from itertools import chain
df_lemmas = pd.DataFrame(list(chain.from_iterable(df_pp["lemmas"])))

In [10]:
df_lemmas.head()

    id  score               value
0  AG1  44.09             educado
1  AG1  38.59           integrado
2  AG1  15.10          equitativo
3  AG2  99.00  ii. aguascalientes
4  AG3  46.59            gobierno

In [11]:
df_syncons = pd.DataFrame(list(chain.from_iterable(df_pp["syncons"])))

In [12]:
df_syncons.head()

    id      lemma  score
0  AG1     cortés  43.09
1  AG1  integrado  38.40
2  AG1      justo  15.69
3  AG2    derecho   5.69
4  AG2     cierto   5.40

In [14]:
df_politic_lemmas = pd.merge(df_pp, df_lemmas, how='inner', on = 'id')

In [19]:
df_politic_lemmas.drop(['lemmas', 'syncons'], axis=1, inplace = True)

In [20]:
df_politic_lemmas.head()

,id,group,description,score,value
0,AG1,1,"i. aguascalientes educado, integrado y equitativo",44.09,educado
1,AG1,1,"i. aguascalientes educado, integrado y equitativo",38.59,integrado
2,AG1,1,"i. aguascalientes educado, integrado y equitativo",15.10,equitativo
3,AG2,1,"ii. aguascalientes derecho, seguro y libre",99.00,ii. aguascalientes
4,AG3,1,"iii. aguascalientes con gobierno íntegro, aust...",46.59,gobierno

In [24]:
df_politic_lemmas.to_csv("politic_lemas.csv")

In [16]:
df_politic_syncons = pd.merge(df_pp, df_syncons, how='inner', on = 'id')

In [22]:
df_politic_syncons.drop(['lemmas', 'syncons'], axis=1, inplace = True)

In [23]:
df_politic_syncons.head()

,id,group,description,lemma,score
0,AG1,1,"i. aguascalientes educado, integrado y equitativo",cortés,43.09
1,AG1,1,"i. aguascalientes educado, integrado y equitativo",integrado,38.40
2,AG1,1,"i. aguascalientes educado, integrado y equitativo",justo,15.69
3,AG2,1,"ii. aguascalientes derecho, seguro y libre",derecho,5.69
4,AG2,1,"ii. aguascalientes derecho, seguro y libre",cierto,5.40

In [25]:
df_politic_syncons.to_csv("politic_syncons.csv")